using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1.QuestionManagers
{
    public class GeneralQuestionManager : BaseQuestionManager
    {
        public GeneralQuestionManager()
        {
            Questions = new List<Question>
            {
                new Question { Hint = "Which country is known as the Land of the Rising Sun?", Answer = "Japan", Category = "General" },
                new Question { Hint = "Who was the first person to walk on the Moon?", Answer = "Neil Armstrong", Category = "General" },
                new Question { Hint = "What is the capital of Italy?", Answer = "Rome", Category = "General" },
                new Question { Hint = "What is the largest planet in our solar system?", Answer = "Jupiter", Category = "General" },
                new Question { Hint = "Who wrote 'Pride and Prejudice'?", Answer = "Jane Austen", Category = "General" },
                new Question { Hint = "What is the chemical symbol for water?", Answer = "H₂O", Category = "General" },
                new Question { Hint = "How many continents are there on Earth?", Answer = "Seven", Category = "General" },
                new Question { Hint = "What is the hardest natural substance on Earth?", Answer = "Diamond", Category = "General" },
                new Question { Hint = "In which city is the famous Eiffel Tower located?", Answer = "Paris", Category = "General" },
                new Question { Hint = "What is the largest ocean on Earth?", Answer = "Pacific Ocean", Category = "General" },
                new Question { Hint = "Which planet is known as the Red Planet?", Answer = "Mars", Category = "General" },
                new Question { Hint = "What is the smallest country in the world by land area?", Answer = "Vatican City", Category = "General" },
                new Question { Hint = "What is the capital of Australia?", Answer = "Canberra", Category = "General" },
                new Question { Hint = "Who painted the Mona Lisa?", Answer = "Leonardo da Vinci", Category = "General" },
                new Question { Hint = "What is the longest river in the world?", Answer = "The Nile", Category = "General" },
                new Question { Hint = "Who wrote the play 'Hamlet'?", Answer = "William Shakespeare", Category = "General" },
                new Question { Hint = "What is the main ingredient in guacamole?", Answer = "Avocado", Category = "General" },
                new Question { Hint = "What is the largest desert in the world?", Answer = "The Antarctic Desert", Category = "General" },
                new Question { Hint = "What is the name of the river that runs through Egypt?", Answer = "The Nile", Category = "General" },
                new Question { Hint = "What is the smallest bone in the human body?", Answer = "The stapes bone (in the ear)", Category = "General" },
                new Question { Hint = "What element has the chemical symbol 'O'?", Answer = "Oxygen", Category = "General" },
                new Question { Hint = "What is the capital of Canada?", Answer = "Ottawa", Category = "General" },
                new Question { Hint = "What is the name of the longest-running Broadway show?", Answer = "The Phantom of the Opera", Category = "General" },
                new Question { Hint = "Which ocean is the largest?", Answer = "The Pacific Ocean", Category = "General" },
                new Question { Hint = "What is the name of the process by which plants make their food?", Answer = "Photosynthesis", Category = "General" },
                new Question { Hint = "What is the largest island in the world?", Answer = "Greenland", Category = "General" },
                new Question { Hint = "Who discovered penicillin?", Answer = "Alexander Fleming", Category = "General" },
                new Question { Hint = "What is the name of the fairy in Peter Pan?", Answer = "Tinker Bell", Category = "General" },
                new Question { Hint = "What is the tallest mountain in the world?", Answer = "Mount Everest", Category = "General" },
                new Question { Hint = "What is the capital of Spain?", Answer = "Madrid", Category = "General" },
                new Question { Hint = "Which element has the chemical symbol 'Na'?", Answer = "Sodium", Category = "General" },
                new Question { Hint = "What is the largest city in the United States by population?", Answer = "New York City", Category = "General" },
                new Question { Hint = "Who is the author of the Harry Potter series?", Answer = "J.K. Rowling", Category = "General" },
                new Question { Hint = "What is the currency of Japan?", Answer = "Yen", Category = "General" },
                new Question { Hint = "What is the main ingredient in traditional sushi?", Answer = "Rice", Category = "General" },
                new Question { Hint = "Who is known as the 'Father of Modern Physics'?", Answer = "Albert Einstein", Category = "General" },
                new Question { Hint = "What is the capital of Germany?", Answer = "Berlin", Category = "General" },
                new Question { Hint = "What is the name of the device used to measure temperature?", Answer = "Thermometer", Category = "General" },
                new Question { Hint = "What is the chemical symbol for gold?", Answer = "Au", Category = "General" },
                new Question { Hint = "What is the largest land animal?", Answer = "African Elephant", Category = "General" },
                new Question { Hint = "What is the name of the closest star to Earth?", Answer = "The Sun", Category = "General" },
                new Question { Hint = "What famous ship sank in 1912 after hitting an iceberg?", Answer = "Titanic", Category = "General" },
                new Question { Hint = "What is the smallest planet in our solar system?", Answer = "Mercury", Category = "General" },
                new Question { Hint = "What is the main language spoken in Brazil?", Answer = "Portuguese", Category = "General" },
                new Question { Hint = "Who is the Greek goddess of wisdom?", Answer = "Athena", Category = "General" },
                new Question { Hint = "What is the chemical symbol for silver?", Answer = "Ag", Category = "General" },
                new Question { Hint = "What is the largest species of shark?", Answer = "Whale Shark", Category = "General" },
                new Question { Hint = "What is the capital city of China?", Answer = "Beijing", Category = "General" },
                new Question { Hint = "Who wrote 'The Great Gatsby'?", Answer = "F. Scott Fitzgerald", Category = "General" },
                new Question { Hint = "What is the capital of South Korea?", Answer = "Seoul", Category = "General" },
                new Question { Hint = "What gas do plants primarily use for photosynthesis?", Answer = "Carbon Dioxide", Category = "General" },
                new Question { Hint = "What is the name of the highest waterfall in the world?", Answer = "Angel Falls", Category = "General" },
                new Question { Hint = "What is the main ingredient in traditional pesto sauce?", Answer = "Basil", Category = "General" },
                new Question { Hint = "Which animal is known for its black and white stripes?", Answer = "Zebra", Category = "General" },
                new Question { Hint = "What is the largest continent by land area?", Answer = "Asia", Category = "General" },
                new Question { Hint = "Who was the 16th President of the United States?", Answer = "Abraham Lincoln", Category = "General" },
                new Question { Hint = "What is the smallest unit of life that can replicate independently?", Answer = "A cell", Category = "General" },
                new Question { Hint = "What planet is known as the 'Evening Star' or 'Morning Star'?", Answer = "Venus", Category = "General" },
                new Question { Hint = "What is the main ingredient in a traditional Caesar salad?", Answer = "Romaine lettuce", Category = "General" },
                new Question { Hint = "What is the name of the famous clock tower in London?", Answer = "Big Ben", Category = "General" },
                new Question { Hint = "Who painted 'The Starry Night'?", Answer = "Vincent van Gogh", Category = "General" },
                new Question { Hint = "What is the capital city of Brazil?", Answer = "Brasília", Category = "General" },
                new Question { Hint = "What type of animal is a Komodo dragon?", Answer = "Lizard", Category = "General" },
                new Question { Hint = "What is the national flower of Japan?", Answer = "Cherry Blossom", Category = "General" },
                new Question { Hint = "What planet is known as the 'Giant Planet'?", Answer = "Jupiter", Category = "General" },
                new Question { Hint = "What is the name of the longest river in South America?", Answer = "The Amazon River", Category = "General" },
                new Question { Hint = "Who wrote 'The Catcher in the Rye'?", Answer = "J.D. Salinger", Category = "General" },
                new Question { Hint = "What is the chemical symbol for helium?", Answer = "He", Category = "General" },
                new Question { Hint = "What is the tallest statue in the world?", Answer = "The Statue of Unity", Category = "General" },
                new Question { Hint = "What is the largest species of penguin?", Answer = "Emperor Penguin", Category = "General" },
                new Question { Hint = "What is the largest organ in the human body?", Answer = "Skin", Category = "General" },
                new Question { Hint = "Who was the first woman to win a Nobel Prize?", Answer = "Marie Curie", Category = "General" },
                new Question { Hint = "What is the name of the sea that is bordered by Europe to the north and Africa to the south?", Answer = "The Mediterranean Sea", Category = "General" },
                new Question { Hint = "What is the name of the famous red rock formation in Australia?", Answer = "Uluru (Ayers Rock)", Category = "General" },
                new Question { Hint = "Who is the author of 'Moby-Dick'?", Answer = "Herman Melville", Category = "General" },
                new Question { Hint = "What is the capital of Egypt?", Answer = "Cairo", Category = "General" },
                new Question { Hint = "What is the main ingredient in traditional French ratatouille?", Answer = "Eggplant", Category = "General" },
                new Question { Hint = "What is the most widely spoken language in the world?", Answer = "Mandarin Chinese", Category = "General" },
                new Question { Hint = "What is the chemical symbol for iron?", Answer = "Fe", Category = "General" },
                new Question { Hint = "Who was the first President of the United States?", Answer = "George Washington", Category = "General" },
                new Question { Hint = "What is the name of the first artificial Earth satellite?", Answer = "Sputnik", Category = "General" },
                new Question { Hint = "What is the main ingredient in traditional Italian risotto?", Answer = "Rice", Category = "General" },
                new Question { Hint = "What is the capital of Russia?", Answer = "Moscow", Category = "General" },
                new Question { Hint = "What is the chemical symbol for potassium?", Answer = "K", Category = "General" },
                new Question { Hint = "What is the largest moon of Saturn?", Answer = "Titan", Category = "General" },
                new Question { Hint = "What is the main ingredient in hummus?", Answer = "Chickpeas", Category = "General" },
                new Question { Hint = "What is the capital of Argentina?", Answer = "Buenos Aires", Category = "General" },
                new Question { Hint = "Who painted the Sistine Chapel ceiling?", Answer = "Michelangelo", Category = "General" },
                new Question { Hint = "What is the largest bone in the human body?", Answer = "Femur", Category = "General" },
                new Question { Hint = "What is the capital of Mexico?", Answer = "Mexico City", Category = "General" },
                new Question { Hint = "Who was the first person to reach the South Pole?", Answer = "Roald Amundsen", Category = "General" },
                new Question { Hint = "What is the chemical symbol for nitrogen?", Answer = "N", Category = "General" },
                new Question { Hint = "What is the name of the largest reef system in the world?", Answer = "The Great Barrier Reef", Category = "General" },
                new Question { Hint = "What is the main ingredient in traditional Greek tzatziki?", Answer = "Yogurt", Category = "General" },
                new Question { Hint = "What is the capital of India?", Answer = "New Delhi", Category = "General" },
                new Question { Hint = "What is the name of the longest river in North America?", Answer = "The Missouri River", Category = "General" },
                new Question { Hint = "Who wrote 'To Kill a Mockingbird'?", Answer = "Harper Lee", Category = "General" },
                new Question { Hint = "What is the chemical symbol for chlorine?", Answer = "Cl", Category = "General" },
                new Question { Hint = "What is the name of the famous prison located on an island in San Francisco Bay?", Answer = "Alcatraz", Category = "General" },
            };
        }

        public override List<Question> GetQuestions()
        {
            return Questions.OrderBy(q => Guid.NewGuid()).Take(15).ToList(); // Randomly select 15 questions
        }
    }
}
