using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1.QuestionManagers
{
    public class LiteratureQuestionManager : BaseQuestionManager
    {
        public LiteratureQuestionManager()
        {
            Questions = new List<Question>
            {
                new Question { Hint = "Who wrote 'Pride and Prejudice'?", Answer = "Jane Austen", Category = "Literature" },
                new Question { Hint = "Who wrote the play 'Hamlet'?", Answer = "William Shakespeare", Category = "Literature" },
                new Question { Hint = "Who wrote 'Pride and Prejudice'?", Answer = "Jane Austen", Category = "Literature" },
                new Question { Hint = "Who wrote 'To Kill a Mockingbird'?", Answer = "Harper Lee", Category = "Literature" },
                new Question { Hint = "Who wrote 'Moby-Dick'?", Answer = "Herman Melville", Category = "Literature" },
                new Question { Hint = "Who wrote '1984'?", Answer = "George Orwell", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Great Gatsby'?", Answer = "F. Scott Fitzgerald", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Catcher in the Rye'?", Answer = "J.D. Salinger", Category = "Literature" },
                new Question { Hint = "Who wrote 'War and Peace'?", Answer = "Leo Tolstoy", Category = "Literature" },
                new Question { Hint = "Who wrote 'Brave New World'?", Answer = "Aldous Huxley", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Odyssey'?", Answer = "Homer", Category = "Literature" },
                new Question { Hint = "Who wrote 'Crime and Punishment'?", Answer = "Fyodor Dostoevsky", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Divine Comedy'?", Answer = "Dante Alighieri", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Brothers Karamazov'?", Answer = "Fyodor Dostoevsky", Category = "Literature" },
                new Question { Hint = "Who wrote 'Anna Karenina'?", Answer = "Leo Tolstoy", Category = "Literature" },
                new Question { Hint = "Who wrote 'Don Quixote'?", Answer = "Miguel de Cervantes", Category = "Literature" },
                new Question { Hint = "Who wrote 'Les Misérables'?", Answer = "Victor Hugo", Category = "Literature" },
                new Question { Hint = "Who wrote 'One Hundred Years of Solitude'?", Answer = "Gabriel García Márquez", Category = "Literature" },
                new Question { Hint = "Who wrote 'Wuthering Heights'?", Answer = "Emily Brontë", Category = "Literature" },
                new Question { Hint = "Who wrote 'Frankenstein'?", Answer = "Mary Shelley", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Hobbit'?", Answer = "J.R.R. Tolkien", Category = "Literature" },
                new Question { Hint = "Who wrote 'Jane Eyre'?", Answer = "Charlotte Brontë", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Adventures of Huckleberry Finn'?", Answer = "Mark Twain", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Picture of Dorian Gray'?", Answer = "Oscar Wilde", Category = "Literature" },
                new Question { Hint = "Who wrote 'Dracula'?", Answer = "Bram Stoker", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Iliad'?", Answer = "Homer", Category = "Literature" },
                new Question { Hint = "Who wrote 'Catch-22'?", Answer = "Joseph Heller", Category = "Literature" },
                new Question { Hint = "Who wrote 'Slaughterhouse-Five'?", Answer = "Kurt Vonnegut", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Sun Also Rises'?", Answer = "Ernest Hemingway", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Grapes of Wrath'?", Answer = "John Steinbeck", Category = "Literature" },
                new Question { Hint = "Who wrote 'Fahrenheit 451'?", Answer = "Ray Bradbury", Category = "Literature" },
                new Question { Hint = "Who wrote 'Lord of the Flies'?", Answer = "William Golding", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Road'?", Answer = "Cormac McCarthy", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Handmaid's Tale'?", Answer = "Margaret Atwood", Category = "Literature" },
                new Question { Hint = "Who wrote 'Beloved'?", Answer = "Toni Morrison", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Catcher in the Rye'?", Answer = "J.D. Salinger", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Kite Runner'?", Answer = "Khaled Hosseini", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Book Thief'?", Answer = "Markus Zusak", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Fault in Our Stars'?", Answer = "John Green", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Shining'?", Answer = "Stephen King", Category = "Literature" },
                new Question { Hint = "Who wrote 'Harry Potter and the Sorcerer's Stone'?", Answer = "J.K. Rowling", Category = "Literature" },
                new Question { Hint = "Who wrote 'A Game of Thrones'?", Answer = "George R.R. Martin", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Chronicles of Narnia'?", Answer = "C.S. Lewis", Category = "Literature" },
                new Question { Hint = "Who wrote 'Moby-Dick'?", Answer = "Herman Melville", Category = "Literature" },
                new Question { Hint = "Who wrote 'A Tale of Two Cities'?", Answer = "Charles Dickens", Category = "Literature" },
                new Question { Hint = "Who wrote 'Great Expectations'?", Answer = "Charles Dickens", Category = "Literature" },
                new Question { Hint = "Who wrote 'Little Women'?", Answer = "Louisa May Alcott", Category = "Literature" },
                new Question { Hint = "Who wrote 'Sense and Sensibility'?", Answer = "Jane Austen", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Old Man and the Sea'?", Answer = "Ernest Hemingway", Category = "Literature" },
                new Question { Hint = "Who wrote 'Brave New World'?", Answer = "Aldous Huxley", Category = "Literature" },
                new Question { Hint = "Who wrote 'Of Mice and Men'?", Answer = "John Steinbeck", Category = "Literature" },
                new Question { Hint = "Who wrote 'Gone with the Wind'?", Answer = "Margaret Mitchell", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Scarlet Letter'?", Answer = "Nathaniel Hawthorne", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Bell Jar'?", Answer = "Sylvia Plath", Category = "Literature" },
                new Question { Hint = "Who wrote 'Life of Pi'?", Answer = "Yann Martel", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Time Traveler's Wife'?", Answer = "Audrey Niffenegger", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Da Vinci Code'?", Answer = "Dan Brown", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Hunger Games'?", Answer = "Suzanne Collins", Category = "Literature" },
                new Question { Hint = "Who wrote 'Divergent'?", Answer = "Veronica Roth", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Maze Runner'?", Answer = "James Dashner", Category = "Literature" },
                new Question { Hint = "Who wrote 'Ender's Game'?", Answer = "Orson Scott Card", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Alchemist'?", Answer = "Paulo Coelho", Category = "Literature" },
                new Question { Hint = "Who wrote 'Memoirs of a Geisha'?", Answer = "Arthur Golden", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Girl with the Dragon Tattoo'?", Answer = "Stieg Larsson", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Lovely Bones'?", Answer = "Alice Sebold", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Help'?", Answer = "Kathryn Stockett", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Secret Life of Bees'?", Answer = "Sue Monk Kidd", Category = "Literature" },
                new Question { Hint = "Who wrote 'Water for Elephants'?", Answer = "Sara Gruen", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Road'?", Answer = "Cormac McCarthy", Category = "Literature" },
                new Question { Hint = "Who wrote 'No Country for Old Men'?", Answer = "Cormac McCarthy", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Goldfinch'?", Answer = "Donna Tartt", Category = "Literature" },
                new Question { Hint = "Who wrote 'Gone Girl'?", Answer = "Gillian Flynn", Category = "Literature" },
                new Question { Hint = "Who wrote 'Big Little Lies'?", Answer = "Liane Moriarty", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Night Circus'?", Answer = "Erin Morgenstern", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Light We Lost'?", Answer = "Jill Santopolo", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Silent Patient'?", Answer = "Alex Michaelides", Category = "Literature" },
                new Question { Hint = "Who wrote 'Circe'?", Answer = "Madeline Miller", Category = "Literature" },
                new Question { Hint = "Who wrote 'Where the Crawdads Sing'?", Answer = "Delia Owens", Category = "Literature" },
                new Question { Hint = "Who wrote 'Eleanor Oliphant Is Completely Fine'?", Answer = "Gail Honeyman", Category = "Literature" },
                new Question { Hint = "Who wrote 'Educated'?", Answer = "Tara Westover", Category = "Literature" },
                new Question { Hint = "Who wrote 'Becoming'?", Answer = "Michelle Obama", Category = "Literature" },
                new Question { Hint = "Who wrote 'Sapiens: A Brief History of Humankind'?", Answer = "Yuval Noah Harari", Category = "Literature" },
                new Question { Hint = "Who wrote 'Thinking, Fast and Slow'?", Answer = "Daniel Kahneman", Category = "Literature" },
                new Question { Hint = "Who wrote 'Atomic Habits'?", Answer = "James Clear", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Power of Habit'?", Answer = "Charles Duhigg", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Subtle Art of Not Giving a F*ck'?", Answer = "Mark Manson", Category = "Literature" },
                new Question { Hint = "Who wrote 'The 7 Habits of Highly Effective People'?", Answer = "Stephen Covey", Category = "Literature" },
                new Question { Hint = "Who wrote 'The 5 Love Languages'?", Answer = "Gary Chapman", Category = "Literature" },
                new Question { Hint = "Who wrote 'The Lean Startup'?", Answer = "Eric Ries", Category = "Literature" },
            };
        }

        public override List<Question> GetQuestions()
        {
            return Questions.OrderBy(q => Guid.NewGuid()).Take(15).ToList(); // Randomly select 15 questions
        }
    }
}
