using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1.QuestionManagers
{
    public class ScienceQuestionManager : BaseQuestionManager
    {
        public ScienceQuestionManager()
        {
            Questions = new List<Question>
            {
                new Question { Hint = "What is the largest planet in our solar system?", Answer = "Jupiter", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for water?", Answer = "H₂O", Category = "Science" },
                new Question { Hint = "What is the hardest natural substance on Earth?", Answer = "Diamond", Category = "Science" },
                new Question { Hint = "What is the largest ocean on Earth?", Answer = "Pacific Ocean", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for water?", Answer = "H2O", Category = "Science" },
                new Question { Hint = "What planet is known as the Red Planet?", Answer = "Mars", Category = "Science" },
                new Question { Hint = "What gas do plants absorb from the atmosphere?", Answer = "Carbon dioxide", Category = "Science" },
                new Question { Hint = "Who proposed the theory of relativity?", Answer = "Albert Einstein", Category = "Science" },
                new Question { Hint = "What is the powerhouse of the cell?", Answer = "Mitochondria", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for gold?", Answer = "Au", Category = "Science" },
                new Question { Hint = "What is the hardest natural substance on Earth?", Answer = "Diamond", Category = "Science" },
                new Question { Hint = "What is the speed of light?", Answer = "299,792,458 meters per second", Category = "Science" },
                new Question { Hint = "Who is known as the father of modern physics?", Answer = "Galileo Galilei", Category = "Science" },
                new Question { Hint = "What planet is closest to the sun?", Answer = "Mercury", Category = "Science" },
                new Question { Hint = "What element does 'O' represent on the periodic table?", Answer = "Oxygen", Category = "Science" },
                new Question { Hint = "What is the main gas found in the Earth's atmosphere?", Answer = "Nitrogen", Category = "Science" },
                new Question { Hint = "What is the most abundant element in the universe?", Answer = "Hydrogen", Category = "Science" },
                new Question { Hint = "Who developed the polio vaccine?", Answer = "Jonas Salk", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for sodium?", Answer = "Na", Category = "Science" },
                new Question { Hint = "What is the nearest star to Earth?", Answer = "The Sun", Category = "Science" },
                new Question { Hint = "What planet is known for its rings?", Answer = "Saturn", Category = "Science" },
                new Question { Hint = "What is the pH level of pure water?", Answer = "7", Category = "Science" },
                new Question { Hint = "What gas do humans exhale?", Answer = "Carbon dioxide", Category = "Science" },
                new Question { Hint = "What is the study of living organisms called?", Answer = "Biology", Category = "Science" },
                new Question { Hint = "What is the largest planet in our solar system?", Answer = "Jupiter", Category = "Science" },
                new Question { Hint = "Who is known as the father of evolution?", Answer = "Charles Darwin", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for iron?", Answer = "Fe", Category = "Science" },
                new Question { Hint = "What part of the cell contains the genetic material?", Answer = "Nucleus", Category = "Science" },
                new Question { Hint = "What is the process by which plants make their food?", Answer = "Photosynthesis", Category = "Science" },
                new Question { Hint = "What is the boiling point of water at sea level?", Answer = "100 degrees Celsius", Category = "Science" },
                new Question { Hint = "What is the common name for sodium chloride?", Answer = "Salt", Category = "Science" },
                new Question { Hint = "What type of bond involves the sharing of electron pairs between atoms?", Answer = "Covalent bond", Category = "Science" },
                new Question { Hint = "What is the heaviest naturally occurring element?", Answer = "Uranium", Category = "Science" },
                new Question { Hint = "What is the smallest unit of life?", Answer = "Cell", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for potassium?", Answer = "K", Category = "Science" },
                new Question { Hint = "Who discovered penicillin?", Answer = "Alexander Fleming", Category = "Science" },
                new Question { Hint = "What is the distance between the Earth and the Sun called?", Answer = "Astronomical Unit", Category = "Science" },
                new Question { Hint = "What is the process of cell division in somatic cells called?", Answer = "Mitosis", Category = "Science" },
                new Question { Hint = "What is the chemical formula for methane?", Answer = "CH4", Category = "Science" },
                new Question { Hint = "What is the branch of science that deals with the classification of living organisms?", Answer = "Taxonomy", Category = "Science" },
                new Question { Hint = "What is the lightest element on the periodic table?", Answer = "Hydrogen", Category = "Science" },
                new Question { Hint = "What is the primary pigment found in plants that absorbs sunlight?", Answer = "Chlorophyll", Category = "Science" },
                new Question { Hint = "Who is known as the father of modern chemistry?", Answer = "Antoine Lavoisier", Category = "Science" },
                new Question { Hint = "What planet is known as the Earth's twin?", Answer = "Venus", Category = "Science" },
                new Question { Hint = "What is the most abundant gas in the Earth's atmosphere?", Answer = "Nitrogen", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for silver?", Answer = "Ag", Category = "Science" },
                new Question { Hint = "What is the process by which a liquid changes into a gas?", Answer = "Evaporation", Category = "Science" },
                new Question { Hint = "What type of rock is formed from molten magma?", Answer = "Igneous rock", Category = "Science" },
                new Question { Hint = "What is the primary component of the sun?", Answer = "Hydrogen", Category = "Science" },
                new Question { Hint = "What is the study of the Earth's atmosphere called?", Answer = "Meteorology", Category = "Science" },
                new Question { Hint = "What is the smallest planet in our solar system?", Answer = "Mercury", Category = "Science" },
                new Question { Hint = "What is the main gas involved in the greenhouse effect?", Answer = "Carbon dioxide", Category = "Science" },
                new Question { Hint = "What is the main organ of the circulatory system?", Answer = "Heart", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for calcium?", Answer = "Ca", Category = "Science" },
                new Question { Hint = "What is the process by which plants release oxygen?", Answer = "Photosynthesis", Category = "Science" },
                new Question { Hint = "What is the largest organ in the human body?", Answer = "Skin", Category = "Science" },
                new Question { Hint = "What is the study of genes and heredity called?", Answer = "Genetics", Category = "Science" },
                new Question { Hint = "What is the powerhouse of the cell?", Answer = "Mitochondria", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for neon?", Answer = "Ne", Category = "Science" },
                new Question { Hint = "What is the primary gas found in the Earth's atmosphere?", Answer = "Nitrogen", Category = "Science" },
                new Question { Hint = "What is the boiling point of water at sea level?", Answer = "100 degrees Celsius", Category = "Science" },
                new Question { Hint = "What is the most abundant element in the Earth's crust?", Answer = "Oxygen", Category = "Science" },
                new Question { Hint = "What is the study of Earth's physical structure and substances?", Answer = "Geology", Category = "Science" },
                new Question { Hint = "What is the smallest particle of an element that retains its properties?", Answer = "Atom", Category = "Science" },
                new Question { Hint = "What is the process by which organisms produce energy in the absence of oxygen?", Answer = "Anaerobic respiration", Category = "Science" },
                new Question { Hint = "What is the main gas exhaled by humans?", Answer = "Carbon dioxide", Category = "Science" },
                new Question { Hint = "What is the largest bone in the human body?", Answer = "Femur", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for helium?", Answer = "He", Category = "Science" },
                new Question { Hint = "What is the main constituent of natural gas?", Answer = "Methane", Category = "Science" },
                new Question { Hint = "What is the name of the galaxy that contains our Solar System?", Answer = "The Milky Way", Category = "Science" },
                new Question { Hint = "What is the study of the human mind and behavior called?", Answer = "Psychology", Category = "Science" },
                new Question { Hint = "What is the process by which plants convert light energy into chemical energy?", Answer = "Photosynthesis", Category = "Science" },
                new Question { Hint = "What is the chemical formula for table salt?", Answer = "NaCl", Category = "Science" },
                new Question { Hint = "What is the closest planet to Earth?", Answer = "Venus", Category = "Science" },
                new Question { Hint = "What is the most common gas in the Earth's atmosphere?", Answer = "Nitrogen", Category = "Science" },
                new Question { Hint = "What is the unit of electrical resistance?", Answer = "Ohm", Category = "Science" },
                new Question { Hint = "What is the main gas found in the Sun?", Answer = "Hydrogen", Category = "Science" },
                new Question { Hint = "What is the study of matter and its interactions?", Answer = "Chemistry", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for lead?", Answer = "Pb", Category = "Science" },
                new Question { Hint = "What is the main function of red blood cells?", Answer = "Transport oxygen", Category = "Science" },
                new Question { Hint = "What is the process by which water vapor turns into liquid water?", Answer = "Condensation", Category = "Science" },
                new Question { Hint = "What is the speed of sound?", Answer = "343 meters per second", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for magnesium?", Answer = "Mg", Category = "Science" },
                new Question { Hint = "What is the most abundant metal in the Earth's crust?", Answer = "Aluminum", Category = "Science" },
                new Question { Hint = "What is the study of stars, planets, and other celestial bodies called?", Answer = "Astronomy", Category = "Science" },
                new Question { Hint = "What is the unit of force?", Answer = "Newton", Category = "Science" },
                new Question { Hint = "What is the chemical symbol for zinc?", Answer = "Zn", Category = "Science" },
                new Question { Hint = "What is the process by which cells release energy from glucose?", Answer = "Cellular respiration", Category = "Science" },
                new Question { Hint = "What is the main gas used by plants during photosynthesis?", Answer = "Carbon dioxide", Category = "Science" },
                new Question { Hint = "What is the primary source of energy for the Earth's climate system?", Answer = "The Sun", Category = "Science" },
                new Question { Hint = "What is the main component of the Earth's core?", Answer = "Iron", Category = "Science" },
                new Question { Hint = "What is the largest moon of Saturn?", Answer = "Titan", Category = "Science" },
                new Question { Hint = "What is the name of the process by which plants lose water vapor through their leaves?", Answer = "Transpiration", Category = "Science" },
                new Question { Hint = "What is the study of fungi called?", Answer = "Mycology", Category = "Science" },
                new Question { Hint = "What is the primary function of white blood cells?", Answer = "Fight infection", Category = "Science" },
            };
        }

        public override List<Question> GetQuestions()
        {
            return Questions.OrderBy(q => Guid.NewGuid()).Take(15).ToList(); // Randomly select 15 questions
        }
    }
}
