//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessGame.Gui.Properties {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "8.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessGame.Gui.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WindowTitle => ResourceManager.GetString("WindowTitle", resourceCulture);
        internal static string GuessPrompt => ResourceManager.GetString("GuessPrompt", resourceCulture);
        internal static string Easy => ResourceManager.GetString("Easy", resourceCulture);
        internal static string Medium => ResourceManager.GetString("Medium", resourceCulture);
        internal static string Hard => ResourceManager.GetString("Hard", resourceCulture);
        internal static string Guess => ResourceManager.GetString("Guess", resourceCulture);
        internal static string TooLow => ResourceManager.GetString("TooLow", resourceCulture);
        internal static string TooHigh => ResourceManager.GetString("TooHigh", resourceCulture);
        internal static string InvalidInput => ResourceManager.GetString("InvalidInput", resourceCulture);
        internal static string Attempts => ResourceManager.GetString("Attempts", resourceCulture);
        internal static string Time => ResourceManager.GetString("Time", resourceCulture);
        internal static string CongratsTitle => ResourceManager.GetString("CongratsTitle", resourceCulture);
        internal static string SuccessMessages => ResourceManager.GetString("SuccessMessages", resourceCulture);
    }
}
